---
title: "Big Data: Tarea 5"
author: "Brian Durán"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Descripción

<p align="justify">
En la clase hablamos sobre definiciones de conceptos, y tratamos de desmenuzar terminos que están comunmente en uso, pero cuya definicion no siempre es tan clara.

Siguiendo el ejercicio que hicimos en grupos en clase (y puedes re-utilizar tus notas) por favor escribe un definicion en tus propias palabras para los siguiente conceptos. Donde aplica, o donde aclara la definicion indica la relación con los demás conceptos.
</p>

 - Business Intelligence
 - Lago de datos
 - Ciencia de Datos
 - Ingenieria de datos
 - Big Data
 - ROLAP
 - ETL
 - Inteligencia Artificial
 
<br>
 
#### Business Intelligence
<p align="justify">
Inteligencia de negocios se refiere a las tecnologías, aplicaciones y prácticas para la recolección, integración y análisis de información de negocios para la toma de decisiones estratégicas.
</p>

<br>

#### Lago de Datos
<p align="justify">
Un lago de datos es un repositorio en el cual se almacenan datos crudos, los cuales se pueden estar almacenando con un propósito a futuro o simplemente para tenerlos a mano.
</p>

<br>

#### Ciencia de Datos
<p align="justify">
La Ciencia de Datos es una diciplina que unifica conocimientos y técnicas del área de la programación, estadística, análisis de datos y aprendizaje de máquina con el propósito de entender y analizar un fenómeno por medio de datos.
</p>

<br>

#### Ingeniería de Datos
<p align="justify">
La ingenería de datos es la encargada de utilizar técnicas programación y herramientos para análizar y procesar información estructurada y no estructurada con el propósito de refinarla y adecuarla a las necesidades de una empresa o proyecto.
</p>

<br>

#### Big Data
<p align="justify">
Un conjunto de datos extremadamente largo, el cual sobrepasa la capacidad computacional disponible. Dichos datos se utilizan para revelar patrones, tendencias y asociaciones especialmente relacionados con el comportamiento humano o interacciones.
</p>

<br>

#### ROLAP
<p align="justify">
Esta metodología se basa en la manipulación de datos almacenados en una base de datos relacional para dar la apariencia de la funcionalidad tradicional de una estructura OLAP.
</p>

<br>

#### ETL
<p align="justify">
Se refiere a un proceso que involucra tres pasos, extraer, trasformar y cargar información. Dicho proceso se utiliza normalmente para crear un data warehouse.
</p>

<br>

#### Inteligencia Artificial
<p align="justify">
La inteligencia artificial es la simulación de procesos del cerebro humano por parte de máquinas, especialmente sistemas informáticos. Estos procesos incluyen el aprendizaje, el razonamiento y la autocorrección
</p>




